services:
  backend:
    image: ghcr.io/suryanadhif/homy-be:v1.0.0
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./logs:/app/logs
    networks:
      - homy-network

  frontend:
    image: ghcr.io/suryanadhif/homy-fe:v1.0.0
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL}
    networks:
      - homy-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - homy-db-data:/var/lib/postgresql/data
    networks:
      - homy-network

volumes:
  homy-db-data:

networks:
  homy-network:
    driver: bridge